### ISSUE TITLE
Is there a way to auto stop threads on drop?

### ISSUE THREAD

**Issue by IgnusG** [mbr/stoppable_thread-rs#1]
I basically have to stop the threads at the end of the block where they live. 

Is there a way to automate this with the Drop trait? Implementing it doesn't work as I can't move out of borrowed content (`self.stop()`) and the trick described [here](https://stackoverflow.com/questions/41331577/joining-a-thread-in-a-method-that-takes-mut-self-like-drop-results-in-cann) doesn't work because the fields are different & private.

*Disclaimer: I picked up rust 2 days ago so I don't have enough skill to know if this is bad practice or not*

**Comment by mbr** [comment]
Does moving the handle into a `stoppable_thread::Stopping` work? Otherwise,
I'd need a slightly longer example. =)

**Comment by IgnusG** [comment]
Cleaning up stale issues - Don't think this is a problem anymore 😅
